#!/bin/bash
clipmenud&
wal -i /home/tajo48/ARCH/photos


for profile in ~/.mozilla/firefox/?*.default-release
do
    cp /home/tajo48/.cache/wal/colors.css $profile/chrome/colors.css
done

# see https://unix.stackexchange.com/a/295652/332452
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# see https://wiki.archlinux.org/title/GNOME/Keyring#xinitrc
eval $(/usr/bin/gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

# see https://github.com/NixOS/nixpkgs/issues/14966#issuecomment-520083836
mkdir -p "$HOME"/.local/share/keyrings


cd /home/tajo48/ARCH/builds/st
sudo make clean install
cd /home/tajo48/ARCH/builds/dmenu
sudo make clean install
cd /home/tajo48/ARCH/builds/dwm
sudo make clean install
#exec xcompmgr -c &
sudo sh /home/tajo48/ARCH/files/bar.sh &
cd /home/tajo48

sudo timedatectl set-local-rtc 1 --adjust-system-clock

#dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

#ssh-agent dwm
exec dwm
clipmenud

