# ~/.zshrc
# Find and set branch name var if in git repository.
source ~/.profile


function git_branch_name()
{
    branch=$(git symbolic-ref HEAD 2> /dev/null | awk 'BEGIN{FS="/"} {print $NF}')
    if [[ $branch == "" ]];
    then
        :
    else
        echo '- ('$branch')'
    fi
}

# Enable substitution in the prompt.
setopt prompt_subst


# alias v="nvim"
alias x="startx"
alias p="ping google.com"
alias u="sh ~/ARCH/files/upgradefiles.sh"
alias suicide="poweroff"
alias gita="git add -A && git commit -m 'update' && git push"
alias github="sh /home/tajo48/ARCH/files/github.sh"
alias pacre="sudo rm /var/lib/pacman/db.lck"
alias BTW="neofetch"
alias btw="neofetch"
alias notflix="sh /home/tajo48/ARCH/files/notflix.sh"
alias wifi="echo 'iwctl → device list → station <device> get-networks → station <device> connect <network name>'"

# Config for prompt. PS1 synonym.
prompt='%2/ $(git_branch_name) > '


alias arch-install="cd ~/ && sudo sh /home/tajo48/ARCH/install.sh"

