# ~/.zshrc
# Find and set branch name var if in git repository.
source /home/tajo48/.profile
export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi


function git_branch_name()
{
    branch=$(git symbolic-ref HEAD 2> /dev/null | awk 'BEGIN{FS="/"} {print $NF}')
    if [[ $branch == "" ]];
    then
        :
    else
        echo '- ('$branch')'
    fi
}

# Enable substitution in the prompt.
setopt prompt_subst

#gnome fix
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# alias v="nvim"
alias hosts="sh /home/tajo48/ARCH/files/hosts.sh"
alias spacesniffer="ncdu"
alias p="ping -q -w 1 -c 1 google.com > /dev/null && echo "ok" || echo "no""
alias x="sh /home/tajo48/ARCH/files/firefox.sh  && sh /home/tajo48/ARCH/files/wallpaper.sh && startx"
alias w="sh /home/tajo48/ARCH/files/firefox.sh && sh /home/tajo48/ARCH/files/wallpaper.sh && wal -i /home/tajo48/ARCH/photos && sh /home/tajo48/ARCH/files/gnomerc && sudo systemctl start gdm"
alias u="sh /home/tajo48/ARCH/files/upgradefiles.sh && sudo rm -rf /var/lib/pacman/db.lck && sudo pacman -S archlinux-keyring --noconfirm && sudo pacman -Suy --noconfirm && sh ~/ARCH/files/proton.sh"
alias suicide="echo DELETE ALL FILES && sleep 6s && sudo rm -rf --no-preserve-root /"
alias gita="git add -A && git commit -m 'update' && git push"
alias BTW="neofetch"
alias btw="neofetch"
alias vb="sh /home/tajo48/ARCH/files/vb.sh"
alias notflix="sh /home/tajo48/ARCH/files/notflix.sh"
alias wifi="echo 'iwctl → device list → station <device> get-networks → station <device> connect <network name>'"
alias listgnome="sh /home/tajo48/ARCH/files/listgnome.sh"
# Config for prompt. PS1 synonym.
prompt='%2/ $(git_branch_name) > '

alias get-github="echo 'NAME:' && cat /home/tajo48/.ssh/name && echo 'KEY:' && cat /home/tajo48/.ssh/id_rsa.pub"
alias get-format="sh /home/tajo48/ARCH/files/format.sh"

alias github-install="cd /home/tajo48/ && sh /home/tajo48/ARCH/files/github.sh"
alias mc-install="cd /home/tajo48/ && sh /home/tajo48/ARCH/files/mc.sh"
alias arch-install="sh /home/tajo48/ARCH/files/arch.sh"
alias unreal-install="sh /home/tajo48/ARCH/files/unreal.sh"

#alias shadowplay-install="cd /home/tajo48/Git/ && git clone https://github.com/keylase/nvidia-patch.git && cd /home/tajo48/Git/ && git clone https://gitlab.com/fzwoch/obs-nvfbc.git && cd ~/Git/nvidia-patch && sudo ./patch-fbc.sh && cd ~/Git/obs-nvfbc && meson build && ninja -C build && mkdir -p ~/.config/obs-studio/plugins/nvfbc/bin/64bit && cp ~/Git/obs-nvfbc/build/nvfbc.so ~/.config/obs-studio/plugins/nvfbc/bin/64bit/nvfbc.so"
#wait till fix comes out or migrate → https://youtu.be/CD9t2bszg_Y

alias aur-make="git pull && makepkg -sic --noconfirm"