# ~/.zshrc
# Find and set branch name var if in git repository.
source ~/.profile

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi


function git_branch_name()
{
    branch=$(git symbolic-ref HEAD 2> /dev/null | awk 'BEGIN{FS="/"} {print $NF}')
    if [[ $branch == "" ]];
    then
        :
    else
        echo '- ('$branch')'
    fi
}

# Enable substitution in the prompt.
setopt prompt_subst


# alias v="nvim"
alias hosts="sh ~/ARCH/files/hosts.sh"
alias p="ping google.com"
alias x="sh ~/ARCH/files/wallpaper.sh && startx"
#NOTE TO FUTURE ME check if wallpaper is set on gnome because im not sure if it works and im too lazy to check
alias w="sh ~/ARCH/files/wallpaper.sh && gsettings set org.gnome.desktop.background picture-uri ARCH/photos/wallpaper.jpg && sudo systemctl start gdm"
alias u="sh ~/ARCH/files/upgradefiles.sh"
alias suicide="poweroff"
alias gita="git add -A && git commit -m 'update' && git push"
alias github="sh ~/ARCH/files/github.sh"
alias pacre="sudo rm -rf /var/lib/pacman/db.lck && sudo pacman -S archlinux-keyring --noconfirm && sudo pacman -Suy --noconfirm"
alias BTW="neofetch"
alias btw="neofetch"
alias notflix="sh ~/ARCH/files/notflix.sh"
alias wifi="echo 'iwctl → device list → station <device> get-networks → station <device> connect <network name>'"
alias fzfwifi="sh ~/ARCH/files/wifi.sh"
# Config for prompt. PS1 synonym.
prompt='%2/ $(git_branch_name) > '


alias arch-install="cd ~/ && sudo sh ~/ARCH/install.sh"

