name: Shell 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  os:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: CollectOsData
      run: |
        sudo apt install neofetch 
        neofetch
    - name: CollectDiscInfo
      run: lsblk -la

    - name: CollectDataInfo
      run: |
        tree /mnt

    - name: Umount
      run: |
        sudo umount /mnt
  

  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Server start
      run: |
        cargo run -- --no-confirm & sleep 10s && curl localhost:7878
